version: "3.8"

services:
  mongo1:
    image: mongo:7.0
    container_name: mongo1
    ports:
      - 30001:27017
    volumes:
      - "mongo1_data:/data/db"

  mongo2:
    image: mongo:7.0
    container_name: mongo2
    ports:
      - 30002:27017
    volumes:
      - "mongo2_data:/data/db"

  mongo3:
    image: mongo:7.0
    container_name: mongo3
    ports:
      - 30003:27017
    volumes:
      - "mongo3_data:/data/db"


volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
